### PR TITLE
Feature/check-box

### PR DESCRIPTION
**Pull request by roshanprajapat-gofynd**
## Redesign wrt JDS guidelines
No props were removed or added.

## Ticket
https://gofynd.atlassian.net/browse/CACL-32

## Storybook updated
Default
Screenshot 2023-01-13 at 7 04 45 PM

Hover
Screenshot 2023-01-13 at 7 04 56 PM

Checked
Screenshot 2023-01-13 at 7 05 05 PM

Checked Hover
Screenshot 2023-01-13 at 7 05 12 PM

### CODE REVIEW

**Comment by ShahRohan27** [comment]
Screenshot 2023-01-16 at 5 14 31 PM

On disabled state the checkbox hover is still working. Please check

**Review by ShahRohan27 — CHANGES_REQUESTED** [review]
Please check the props and remove the ones that aren't used. 
For example. 

What is the use of `name`

**Comment by roshanprajapat-gofynd** [comment]
Use of `name` 
https://reactjs.org/docs/components-and-props.html

**Comment by ShahRohan27** [comment]
Approved 👍

**Pull request merged**
