### PR TITLE
feat(feature/modal): added modal component changes as per updated des…

### PR DESCRIPTION
**Pull request by RupeshAagde-fynd**
…ign)

### CODE REVIEW

**Comment by RupeshAagde-fynd** [comment]
Screenshot 2023-02-01 at 2 31 35 PM

kind: "information" , size : "s"

**Comment by RupeshAagde-fynd** [comment]
Screenshot 2023-02-01 at 2 31 19 PM

**Comment by RupeshAagde-fynd** [comment]
Screenshot 2023-02-01 at 2 31 10 PM


kind : "acknowledgement" , size : "s"

**Comment by RupeshAagde-fynd** [comment]
Screenshot 2023-02-01 at 2 30 56 PM


kind : "acknowledgement" , size : "m"

**Comment by RupeshAagde-fynd** [comment]
Screenshot 2023-02-01 at 2 30 39 PM


kind : "dialog" , size : "s"

**Comment by RupeshAagde-fynd** [comment]
Screenshot 2023-02-01 at 2 30 12 PM


kind : "dialog" , size : "m"

**Comment by ShahRohan27** [comment]
@RupeshAagde-fynd Use rem instead of px. Base font-size is set to 10px, rest all looks good. Have you tested it properly on mobile views?

**Comment by RupeshAagde-fynd** [comment]
New props added for JDS compliant changes

* kind (Types of Modal : "dialog" | "acknowledgement" | "informational")
* title: (Now we can pass string as well as object in title). object format = {helperBlock: {children},titleBlock : {children}}
* size: "s" | "m"
* isClosable

**Comment by RupeshAagde-fynd** [comment]
Screenshot 2023-02-01 at 2 53 19 PM


isClosable : false (will not able to see close btn)

**Pull request merged**
